tasks:
  - name: enable redis:7
    ansible.builtin.command: dnf module enable redis:7 -y
    
  - name: installing redis:7
    ansible.builtin.dnf:
      name: redis
      state: present
  - name: allowing connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'
      
  - name: enabling and starting the redis
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: started