- name:  install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: present
- name: Enabling and starting Mysqld
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
- name: setting root password for mysql
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"