- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql
  
- name: installing dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: moving jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app