- name: Enabling new nodejs modules
  ansible.builtin.command: dnf module enable nodejs:20 -y
  
- name: Install nodejs
  tags:
  - deployment
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install nodejs dependencies
  tags:
  - deployment
  community.general.npm:
    path: /app