- name: Copy service repo
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
    
- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reexec: true